import os
import json
import uuid
from datetime import datetime, timezone
from dotenv import load_dotenv
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

# Load environment variables
load_dotenv()

# Initialize Flask app
app = Flask(__name__)

# Initialize rate limiter
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# Initialize Groq client
groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# Audit log file path
LOG_FILE = "audit_log.json"


# ─────────────────────────────────────────
# AUDIT LOG HELPERS
# ─────────────────────────────────────────

def read_log():
    """Read all entries from the audit log."""
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return []


def write_log(entry):
    """Append a new entry to the audit log."""
    entries = read_log()
    entries.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


# ─────────────────────────────────────────
# SIGNAL 1: GROQ LLM CLASSIFICATION
# ─────────────────────────────────────────

def get_llm_score(text):
    """
    Send text to Groq LLM and get a score from 0.0 to 1.0.
    1.0 = very likely AI-generated
    0.0 = very likely human-written
    Returns a float.
    """
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by an AI writing tool.

Analyze the following text carefully. Consider:
- Phrasing patterns (AI tends to be smooth and generic)
- Structural uniformity (AI tends to have consistent paragraph structure)
- Personal voice and idiosyncrasies (humans have these, AI rarely does)
- Vocabulary and transitions (AI overuses certain connective phrases)

Text to analyze:
\"\"\"
{text}
\"\"\"

Respond with ONLY a JSON object in this exact format, nothing else:
{{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence explanation>"}}

Where ai_probability is:
- 0.9 to 1.0: almost certainly AI-generated
- 0.7 to 0.89: likely AI-generated
- 0.35 to 0.69: uncertain, could be either
- 0.15 to 0.34: likely human-written
- 0.0 to 0.14: almost certainly human-written"""

    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=150,
        )
        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        parsed = json.loads(raw)
        score = float(parsed["ai_probability"])

        # Clamp to valid range
        score = max(0.0, min(1.0, score))
        return score, parsed.get("reasoning", "No reasoning provided")

    except Exception as e:
        print(f"LLM signal error: {e}")
        return 0.5, "Error during LLM analysis — defaulting to uncertain"



# ─────────────────────────────────────────
# SIGNAL 2: STYLOMETRIC HEURISTICS
# ─────────────────────────────────────────

def get_style_score(text):
    """
    Compute stylometric heuristics to detect AI-generated text.
    Measures 3 properties:
    1. Sentence length variance (low variance = AI-like)
    2. Type-token ratio (low TTR = AI-like)
    3. Punctuation density (low density = AI-like)
    Returns a float 0.0-1.0 where 1.0 = very AI-like, 0.0 = very human-like.
    """
    import re
    import math

    # ── Sentence length variance ──
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    if len(sentences) < 2:
        # Too short to measure variance reliably
        sentence_variance_score = 0.5
    else:
        lengths = [len(s.split()) for s in sentences]
        mean_len = sum(lengths) / len(lengths)
        variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
        std_dev = math.sqrt(variance)
        # High std_dev = human-like variation, low = AI-like uniformity
        # Normalize: std_dev of 0-3 = AI-like (score near 1.0), 10+ = human-like (score near 0.0)
        sentence_variance_score = max(0.0, min(1.0, 1.0 - (std_dev / 10.0)))

    # ── Type-token ratio (TTR) ──
    words = re.findall(r'\b\w+\b', text.lower())
    if len(words) == 0:
        ttr_score = 0.5
    else:
        unique_words = set(words)
        ttr = len(unique_words) / len(words)
        # High TTR = human-like diversity, low TTR = AI-like repetition
        # TTR below 0.6 = AI-like (score near 1.0), above 0.85 = human-like (score near 0.0)
        ttr_score = max(0.0, min(1.0, 1.0 - (ttr / 0.9)))
    # ── Punctuation density ──
    punctuation_marks = re.findall(r'[!?;:\-—…"]', text)
    word_count = len(words) if len(words) > 0 else 1
    punct_density = len(punctuation_marks) / word_count
    # Low punctuation density = AI-like (score near 1.0), high = human-like (score near 0.0)
    # density of 0 = AI-like, 0.1+ = human-like
    punct_score = max(0.0, min(1.0, 1.0 - (punct_density / 0.1)))

    # ── Combine three metrics into one style score ──
    style_score = round((sentence_variance_score + ttr_score + punct_score) / 3, 4)
    return style_score, {
        "sentence_variance_score": round(sentence_variance_score, 4),
        "ttr_score": round(ttr_score, 4),
        "punct_score": round(punct_score, 4),
    }


# ─────────────────────────────────────────
# CONFIDENCE SCORING
# ─────────────────────────────────────────

def get_confidence_score(llm_score, style_score):
    """
    Combine LLM and stylometric signals into a final confidence score.
    Weighting: 60% LLM + 40% stylometrics (as defined in planning.md)
    """
    return round((llm_score * 0.60) + (style_score * 0.40), 4)


# ─────────────────────────────────────────
# TRANSPARENCY LABEL (placeholder for M5)
# ─────────────────────────────────────────

def get_label(confidence):
    """
    Map confidence score to transparency label.
    Placeholder in M3 — full label text added in M5.
    """
    if confidence >= 0.85:
        return "Likely AI-Generated"
    elif confidence <= 0.14:
        return "Likely Human-Written"
    else:
        return "Attribution Uncertain"


# ─────────────────────────────────────────
# ATTRIBUTION RESULT
# ─────────────────────────────────────────

def get_attribution(confidence):
    """Map confidence score to attribution string."""
    if confidence >= 0.50:
        return "likely_ai"
    else:
        return "likely_human"


# ─────────────────────────────────────────
# ROUTES
# ─────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    """
    POST /submit
    Accepts: { text, creator_id }
    Returns: { content_id, attribution, confidence, label, llm_score, timestamp }
    """
    data = request.get_json()

    # Validate input
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Request must include 'text' and 'creator_id' fields"}), 400

    text = data["text"].strip()
    creator_id = data["creator_id"].strip()

    if not text:
        return jsonify({"error": "Text field cannot be empty"}), 400

    # Generate unique content ID
    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

   # Run Signal 1: Groq LLM
    llm_score, llm_reasoning = get_llm_score(text)

    # Run Signal 2: Stylometric heuristics
    style_score, style_breakdown = get_style_score(text)

    # Confidence score: 60% LLM + 40% stylometrics
    confidence = get_confidence_score(llm_score, style_score)

    # Attribution result and label
    attribution = get_attribution(confidence)
    label = get_label(confidence)

    # Write to audit log
    # Write to audit log
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "llm_reasoning": llm_reasoning,
        "style_score": style_score,
        "style_breakdown": style_breakdown,
        "label": label,
        "status": "classified",
        "appeal_reasoning": None,
    }
    write_log(log_entry)

    # Return response
    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "llm_score": llm_score,
        "style_score": style_score,
        "style_breakdown": style_breakdown,
        "timestamp": timestamp,
    })


@app.route("/log", methods=["GET"])
def get_log():
    """
    GET /log
    Returns the most recent audit log entries as JSON.
    """
    entries = read_log()
    # Return most recent 20 entries
    recent = entries[-20:] if len(entries) > 20 else entries
    return jsonify({"entries": recent, "total": len(entries)})


# ─────────────────────────────────────────
# RUN
# ─────────────────────────────────────────

if __name__ == "__main__":
    app.run(debug=True)
